# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do

  # Lane for SwiftLint check
  # desc "Run SwiftLint"
  # lane :lint do
  #   swiftlint(
  #     mode: :lint,
  #     strict: false,
  #     config_file: '.swiftlint.yml',
  #     reporter: 'xcode'
  #   )
  # end

  # Lane for git operations
  desc "Git: clean, pull, and push"
  lane :git_sync do
    ensure_git_status_clean
    git_pull
    push_to_git_remote
  end

  # Lane for incrementing build number
  # desc "Increment build number"
  # lane :increment do
  #   increment_build_number
  # end

  # Lane for building the app
  desc "Build the app"
  lane :build do
    increment
    cocoapods # Ensure pods are up to date
    build_ios_app(
      scheme: "EkyWeather",
      workspace: "EkyWeather.xcworkspace",
      configuration: "Debug",
      clean: true,
      skip_package_dependencies_resolution: true
    )
  end

  # Lane for testing the app
  # desc "Run tests"
  # lane :test do
  #   run_tests(
  #     scheme: "EkyWeather",
  #     workspace: "EkyWeather.xcworkspace",
  #     clean: true,
  #     devices: ["iPhone 14"],
  #     code_coverage: true,
  #     result_bundle: true
  #   )
  # end

  # Lane for deploying to simulator
  # desc "Deploy to simulator"
  # lane :deploy_simulator do
  #   build_ios_app(
  #     scheme: "EkyWeather",
  #     workspace: "EkyWeather.xcworkspace",
  #     configuration: "Debug",
  #     destination: "platform=iOS Simulator,name=iPhone 14",
  #     skip_package_dependencies_resolution: true
  #   )
  #   sh("xcrun simctl install booted ../build/EkyWeather.app")
  #   sh("xcrun simctl launch booted com.rizkydarma.EkyWeather")
  # end

  # Lane for complete development workflow
  desc "Complete development workflow: lint, test, build, and deploy to simulator"
  lane :dev do
    lint
    git_sync
    # test
    deploy_simulator
  end

  # Lane for CI process
  desc "Continuous Integration process"
  lane :ci do
    lint
    # test
    build
  end
end