# Name of the workflow
name: iOS CI

# Triggers - when this workflow will run
on:
  push:
    branches: [ "main" ]  # Triggers on push to main branch
  pull_request:
    branches: [ "main" ]  # Triggers on PRs to main branch

# Jobs to run
jobs:
  build:
    name: Build
    runs-on: macos-latest  # Using latest macOS runner

    steps:
    # Step 1: Check out the repository
    - name: Checkout Repository
      uses: actions/checkout@v4

    # Step 2: Setup Xcode version
    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: 'latest-stable'

    # Step 3: Setup Swift
    - name: Setup Swift
      uses: swift-actions/setup-swift@65540b95f51493d65f5e59e97dcef9629ddf11bf
      with:
        swift-version: "5.9"

    # Step 4: Show Swift version
    - name: Show Swift Version
      run: swift --version

    # Step 5: Build the project
    - name: Build Swift Package
      run: swift build -v

    # Step 7: Build for iOS (if using Xcode project)
    - name: Build iOS App
      run: |
        xcodebuild clean build -scheme "${SCHEME_NAME}" -destination "platform=iOS Simulator,name=iPhone 14 Pro"
      env:
        SCHEME_NAME: EkyWeather