# Name of the workflow
name: iOS CI

# Triggers - when this workflow will run
on:
  push:
    branches: [ "main" ]  # Triggers on push to main branch
  pull_request:
    branches: [ "main" ]  # Triggers on PRs to main branch

# Jobs to run
jobs:
  build:
    name: Build
    runs-on: macos-latest  # Using latest macOS runner

    steps:
    # Step 1: Check out the repository
    - name: Checkout Repository
      uses: actions/checkout@v4

    # Step 2: Setup Xcode version
    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: 'latest-stable'

    - name: Install Apple Certificate
      run: |
        sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
        sudo xcodebuild -runFirstLaunch

    # Step 7: Build for iOS (if using Xcode project)
    - name: Build iOS App
      run: |
        xcodebuild clean build -scheme "${SCHEME_NAME}" -destination "platform=iOS Simulator,OS=18.2,name=iPhone 15"
      env:
        SCHEME_NAME: EkyWeather